export function getLegacyPostRedirections(): Record<string, string> {
  const legacyPostsUrls = [
    'commandes-sf2',
    'vagrant',
    'hadopi',
    'rest-rmm-model',
    'utilisez-un-framework-php',
    'atom',
    'rest-crud',
    'a-la-decouverte-d-apispark',
    'productivite-ninja',
    'cache-doctrine-avec-redis',
    'docker-pour-symfony',
    'qualite-logicielle-3-petits-cochons',
    'vagrant-symfony-windows',
    'dealing-with-enum-symfony-doctrine',
    'else-unnecessary-expression',
    'programmation-fonctionnelle-php',
    '2016-a-year-in-review',
    'github-tips-and-tricks',
    'no-more-loop-in-js',
    'chaining-filter-js',
    'expatriation-en-irlande',
    'hubot',
    'js-exercises-explained',
    'immutability-js-without-library',
    'hello-gatsby',
    'nomad-in-lisbon',
    '3-tips-scaling-vue-application',
    '2018-a-year-in-review',
    'git-conventional-commits',
    'nomad-in-canggu',
    'busting-nomad-myths',
    'busting-nomad-myths-fr',
    'git-under-the-hood',
    'jest-mock-date',
    'git-cheat-sheet',
    '2019-a-year-in-review',
    'generate-social-image-share-with-gatsby',
    '10-tips-write-better-tests',
    '10-tips-for-working-from-home',
    '10-tips-for-working-from-home-fr',
    'code-coverage',
    'async-await-without-try-catch',
    'async-await-without-try-catch-fr',
    'jest-mock-axios-calls',
    'vue-js-testing-library',
    'vuejs-performance-improvement-with-memoization',
    'tips-for-your-github-portfolio',
    'monorepo-pros-and-cons-fr',
    'monorepo-pros-and-cons',
    '2020-a-year-in-review',
    'bash-for-dev',
    'lesson-learned-maintaining-large-vue-js-codebase',
    'vue-js-module-architecture',
    'rsi-as-developer',
    '2021-a-year-in-review',
    'git-worktrees',
    'turborepo',
    'aoe2-on-macos',
    'publish-npm-package-esm-and-cjs',
    'improving-core-web-vitals-react-app',
  ]

  const redirections: Record<string, string> = {}
  for (const legacyUrl of legacyPostsUrls) {
    redirections[legacyUrl] = `/blog/${legacyUrl}`
  }
  return redirections
}
